// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(WebAPIDBContext))]
    [Migration("20260722010605_AddAvatarStudioTables")]
    partial class AddAvatarStudioTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("backend.Models.AvatarEquippedItem", b =>
                {
                    b.Property<int>("AvatarEquippedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL");

                    b.Property<double>("Scale")
                        .HasColumnType("REAL");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TortoiseAvatarId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<int>("ZIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("AvatarEquippedItemId");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("TortoiseAvatarId", "ShopItemId")
                        .IsUnique();

                    b.ToTable("AvatarEquippedItems");
                });

            modelBuilder.Entity("backend.Models.DailyCareTask", b =>
                {
                    b.Property<int>("DailyCareTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoinReward")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TaskDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TortoiseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpReward")
                        .HasColumnType("INTEGER");

                    b.HasKey("DailyCareTaskId");

                    b.HasIndex("TortoiseId");

                    b.HasIndex("OwnerId", "TortoiseId", "TaskType", "TaskDate")
                        .IsUnique();

                    b.ToTable("DailyCareTasks");
                });

            modelBuilder.Entity("backend.Models.PurchaseTransaction", b =>
                {
                    b.Property<int>("PurchaseTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PricePaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PurchaseTransactionId");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("OwnerId", "PurchasedAt");

                    b.ToTable("PurchaseTransactions");
                });

            modelBuilder.Entity("backend.Models.ShopItem", b =>
                {
                    b.Property<int>("ShopItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultRotation")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultScale")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultX")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultY")
                        .HasColumnType("REAL");

                    b.Property<int>("DefaultZIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("ShopItemId");

                    b.HasIndex("AssetKey")
                        .IsUnique();

                    b.ToTable("ShopItems");
                });

            modelBuilder.Entity("backend.Models.Tortoise", b =>
                {
                    b.Property<int>("TortoiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgeMonths")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeightGrams")
                        .HasColumnType("TEXT");

                    b.HasKey("TortoiseId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Tortoises");
                });

            modelBuilder.Entity("backend.Models.TortoiseAvatar", b =>
                {
                    b.Property<int>("TortoiseAvatarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanvasHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanvasWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TortoiseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TortoiseAvatarId");

                    b.HasIndex("TortoiseId")
                        .IsUnique();

                    b.ToTable("TortoiseAvatars");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastActiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalXp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.UserAchievement", b =>
                {
                    b.Property<int>("UserAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AchievementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserAchievementId");

                    b.HasIndex("OwnerId", "AchievementType")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("backend.Models.UserInventoryItem", b =>
                {
                    b.Property<int>("UserInventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserInventoryItemId");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("OwnerId", "ShopItemId")
                        .IsUnique();

                    b.ToTable("UserInventoryItems");
                });

            modelBuilder.Entity("backend.Models.AvatarEquippedItem", b =>
                {
                    b.HasOne("backend.Models.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.TortoiseAvatar", "TortoiseAvatar")
                        .WithMany("EquippedItems")
                        .HasForeignKey("TortoiseAvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");

                    b.Navigation("TortoiseAvatar");
                });

            modelBuilder.Entity("backend.Models.DailyCareTask", b =>
                {
                    b.HasOne("backend.Models.User", "Owner")
                        .WithMany("DailyCareTasks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Tortoise", "Tortoise")
                        .WithMany("DailyCareTasks")
                        .HasForeignKey("TortoiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Tortoise");
                });

            modelBuilder.Entity("backend.Models.PurchaseTransaction", b =>
                {
                    b.HasOne("backend.Models.User", "Owner")
                        .WithMany("Purchases")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ShopItem", "ShopItem")
                        .WithMany("Purchases")
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ShopItem");
                });

            modelBuilder.Entity("backend.Models.Tortoise", b =>
                {
                    b.HasOne("backend.Models.User", "Owner")
                        .WithMany("Tortoises")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("backend.Models.TortoiseAvatar", b =>
                {
                    b.HasOne("backend.Models.Tortoise", "Tortoise")
                        .WithOne()
                        .HasForeignKey("backend.Models.TortoiseAvatar", "TortoiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tortoise");
                });

            modelBuilder.Entity("backend.Models.UserAchievement", b =>
                {
                    b.HasOne("backend.Models.User", "Owner")
                        .WithMany("Achievements")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("backend.Models.UserInventoryItem", b =>
                {
                    b.HasOne("backend.Models.User", "Owner")
                        .WithMany("InventoryItems")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ShopItem", "ShopItem")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ShopItem");
                });

            modelBuilder.Entity("backend.Models.ShopItem", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("backend.Models.Tortoise", b =>
                {
                    b.Navigation("DailyCareTasks");
                });

            modelBuilder.Entity("backend.Models.TortoiseAvatar", b =>
                {
                    b.Navigation("EquippedItems");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("DailyCareTasks");

                    b.Navigation("InventoryItems");

                    b.Navigation("Purchases");

                    b.Navigation("Tortoises");
                });
#pragma warning restore 612, 618
        }
    }
}
